insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("노트북", "electronics", 500000, "삼성", 20, "최신형")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("티비", "electronics", 1000000, "LG", 34, "HD")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("옷장", "furniture", 1200000, "삼성", 5, "스마트옷장")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("테이블", "furniture", 50000, "이케아", 200, "케나다 목재")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("의자", "furniture", 25000, "삼성", 350, "케나다 목재")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("핸드폰", "electronics", 900000, "삼성", 20, "5G")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("에어팟", "electronics", 120000, "애플", 110, "세일")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("컵", "ext", 3000, "다이소", 13, "유리")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("가위", "ext", 1000, "다이소", 280, "미용가위")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("마이크", "ext", 50000, "LG", 50, "블루투스")